#!/bin/bash
#PBS -N pmv-b1
#PBS -q ac

N=1000

export OMP_NUM_THREADS=1
echo "1 PROCESADOR";
$PBS_O_WORKDIR/pmv-OpenMP-b $N
$PBS_O_WORKDIR/pmv-OpenMP-b $N
$PBS_O_WORKDIR/pmv-OpenMP-b $N
$PBS_O_WORKDIR/pmv-OpenMP-b $N
$PBS_O_WORKDIR/pmv-OpenMP-b $N
$PBS_O_WORKDIR/pmv-OpenMP-b $N
$PBS_O_WORKDIR/pmv-OpenMP-b $N
$PBS_O_WORKDIR/pmv-OpenMP-b $N
$PBS_O_WORKDIR/pmv-OpenMP-b $N
$PBS_O_WORKDIR/pmv-OpenMP-b $N
$PBS_O_WORKDIR/pmv-OpenMP-b $N
$PBS_O_WORKDIR/pmv-OpenMP-b $N
$PBS_O_WORKDIR/pmv-OpenMP-b $N
$PBS_O_WORKDIR/pmv-OpenMP-b $N
$PBS_O_WORKDIR/pmv-OpenMP-b $N
$PBS_O_WORKDIR/pmv-OpenMP-b $N
$PBS_O_WORKDIR/pmv-OpenMP-b $N
$PBS_O_WORKDIR/pmv-OpenMP-b $N
$PBS_O_WORKDIR/pmv-OpenMP-b $N
$PBS_O_WORKDIR/pmv-OpenMP-b $N
export OMP_NUM_THREADS=2
echo "2 PROCESADOR";
$PBS_O_WORKDIR/pmv-OpenMP-b $N
$PBS_O_WORKDIR/pmv-OpenMP-b $N
$PBS_O_WORKDIR/pmv-OpenMP-b $N
$PBS_O_WORKDIR/pmv-OpenMP-b $N
$PBS_O_WORKDIR/pmv-OpenMP-b $N
$PBS_O_WORKDIR/pmv-OpenMP-b $N
$PBS_O_WORKDIR/pmv-OpenMP-b $N
$PBS_O_WORKDIR/pmv-OpenMP-b $N
$PBS_O_WORKDIR/pmv-OpenMP-b $N
$PBS_O_WORKDIR/pmv-OpenMP-b $N
$PBS_O_WORKDIR/pmv-OpenMP-b $N
$PBS_O_WORKDIR/pmv-OpenMP-b $N
$PBS_O_WORKDIR/pmv-OpenMP-b $N
$PBS_O_WORKDIR/pmv-OpenMP-b $N
$PBS_O_WORKDIR/pmv-OpenMP-b $N
$PBS_O_WORKDIR/pmv-OpenMP-b $N
$PBS_O_WORKDIR/pmv-OpenMP-b $N
$PBS_O_WORKDIR/pmv-OpenMP-b $N
$PBS_O_WORKDIR/pmv-OpenMP-b $N
$PBS_O_WORKDIR/pmv-OpenMP-b $N
export OMP_NUM_THREADS=3
echo "3 PROCESADOR";
$PBS_O_WORKDIR/pmv-OpenMP-b $N
$PBS_O_WORKDIR/pmv-OpenMP-b $N
$PBS_O_WORKDIR/pmv-OpenMP-b $N
$PBS_O_WORKDIR/pmv-OpenMP-b $N
$PBS_O_WORKDIR/pmv-OpenMP-b $N
$PBS_O_WORKDIR/pmv-OpenMP-b $N
$PBS_O_WORKDIR/pmv-OpenMP-b $N
$PBS_O_WORKDIR/pmv-OpenMP-b $N
$PBS_O_WORKDIR/pmv-OpenMP-b $N
$PBS_O_WORKDIR/pmv-OpenMP-b $N
$PBS_O_WORKDIR/pmv-OpenMP-b $N
$PBS_O_WORKDIR/pmv-OpenMP-b $N
$PBS_O_WORKDIR/pmv-OpenMP-b $N
$PBS_O_WORKDIR/pmv-OpenMP-b $N
$PBS_O_WORKDIR/pmv-OpenMP-b $N
$PBS_O_WORKDIR/pmv-OpenMP-b $N
$PBS_O_WORKDIR/pmv-OpenMP-b $N
$PBS_O_WORKDIR/pmv-OpenMP-b $N
$PBS_O_WORKDIR/pmv-OpenMP-b $N
$PBS_O_WORKDIR/pmv-OpenMP-b $N
export OMP_NUM_THREADS=4
echo "4 PROCESADOR";
$PBS_O_WORKDIR/pmv-OpenMP-b $N
$PBS_O_WORKDIR/pmv-OpenMP-b $N
$PBS_O_WORKDIR/pmv-OpenMP-b $N
$PBS_O_WORKDIR/pmv-OpenMP-b $N
$PBS_O_WORKDIR/pmv-OpenMP-b $N
$PBS_O_WORKDIR/pmv-OpenMP-b $N
$PBS_O_WORKDIR/pmv-OpenMP-b $N
$PBS_O_WORKDIR/pmv-OpenMP-b $N
$PBS_O_WORKDIR/pmv-OpenMP-b $N
$PBS_O_WORKDIR/pmv-OpenMP-b $N
$PBS_O_WORKDIR/pmv-OpenMP-b $N
$PBS_O_WORKDIR/pmv-OpenMP-b $N
$PBS_O_WORKDIR/pmv-OpenMP-b $N
$PBS_O_WORKDIR/pmv-OpenMP-b $N
$PBS_O_WORKDIR/pmv-OpenMP-b $N
$PBS_O_WORKDIR/pmv-OpenMP-b $N
$PBS_O_WORKDIR/pmv-OpenMP-b $N
$PBS_O_WORKDIR/pmv-OpenMP-b $N
$PBS_O_WORKDIR/pmv-OpenMP-b $N
$PBS_O_WORKDIR/pmv-OpenMP-b $N
export OMP_NUM_THREADS=5
echo "5 PROCESADOR";
$PBS_O_WORKDIR/pmv-OpenMP-b $N
$PBS_O_WORKDIR/pmv-OpenMP-b $N
$PBS_O_WORKDIR/pmv-OpenMP-b $N
$PBS_O_WORKDIR/pmv-OpenMP-b $N
$PBS_O_WORKDIR/pmv-OpenMP-b $N
$PBS_O_WORKDIR/pmv-OpenMP-b $N
$PBS_O_WORKDIR/pmv-OpenMP-b $N
$PBS_O_WORKDIR/pmv-OpenMP-b $N
$PBS_O_WORKDIR/pmv-OpenMP-b $N
$PBS_O_WORKDIR/pmv-OpenMP-b $N
$PBS_O_WORKDIR/pmv-OpenMP-b $N
$PBS_O_WORKDIR/pmv-OpenMP-b $N
$PBS_O_WORKDIR/pmv-OpenMP-b $N
$PBS_O_WORKDIR/pmv-OpenMP-b $N
$PBS_O_WORKDIR/pmv-OpenMP-b $N
$PBS_O_WORKDIR/pmv-OpenMP-b $N
$PBS_O_WORKDIR/pmv-OpenMP-b $N
$PBS_O_WORKDIR/pmv-OpenMP-b $N
$PBS_O_WORKDIR/pmv-OpenMP-b $N
$PBS_O_WORKDIR/pmv-OpenMP-b $N
export OMP_NUM_THREADS=6
echo "6 PROCESADOR";
$PBS_O_WORKDIR/pmv-OpenMP-b $N
$PBS_O_WORKDIR/pmv-OpenMP-b $N
$PBS_O_WORKDIR/pmv-OpenMP-b $N
$PBS_O_WORKDIR/pmv-OpenMP-b $N
$PBS_O_WORKDIR/pmv-OpenMP-b $N
$PBS_O_WORKDIR/pmv-OpenMP-b $N
$PBS_O_WORKDIR/pmv-OpenMP-b $N
$PBS_O_WORKDIR/pmv-OpenMP-b $N
$PBS_O_WORKDIR/pmv-OpenMP-b $N
$PBS_O_WORKDIR/pmv-OpenMP-b $N
$PBS_O_WORKDIR/pmv-OpenMP-b $N
$PBS_O_WORKDIR/pmv-OpenMP-b $N
$PBS_O_WORKDIR/pmv-OpenMP-b $N
$PBS_O_WORKDIR/pmv-OpenMP-b $N
$PBS_O_WORKDIR/pmv-OpenMP-b $N
$PBS_O_WORKDIR/pmv-OpenMP-b $N
$PBS_O_WORKDIR/pmv-OpenMP-b $N
$PBS_O_WORKDIR/pmv-OpenMP-b $N
$PBS_O_WORKDIR/pmv-OpenMP-b $N
$PBS_O_WORKDIR/pmv-OpenMP-b $N
export OMP_NUM_THREADS=7
echo "7 PROCESADOR";
$PBS_O_WORKDIR/pmv-OpenMP-b $N
$PBS_O_WORKDIR/pmv-OpenMP-b $N
$PBS_O_WORKDIR/pmv-OpenMP-b $N
$PBS_O_WORKDIR/pmv-OpenMP-b $N
$PBS_O_WORKDIR/pmv-OpenMP-b $N
$PBS_O_WORKDIR/pmv-OpenMP-b $N
$PBS_O_WORKDIR/pmv-OpenMP-b $N
$PBS_O_WORKDIR/pmv-OpenMP-b $N
$PBS_O_WORKDIR/pmv-OpenMP-b $N
$PBS_O_WORKDIR/pmv-OpenMP-b $N
$PBS_O_WORKDIR/pmv-OpenMP-b $N
$PBS_O_WORKDIR/pmv-OpenMP-b $N
$PBS_O_WORKDIR/pmv-OpenMP-b $N
$PBS_O_WORKDIR/pmv-OpenMP-b $N
$PBS_O_WORKDIR/pmv-OpenMP-b $N
$PBS_O_WORKDIR/pmv-OpenMP-b $N
$PBS_O_WORKDIR/pmv-OpenMP-b $N
$PBS_O_WORKDIR/pmv-OpenMP-b $N
$PBS_O_WORKDIR/pmv-OpenMP-b $N
$PBS_O_WORKDIR/pmv-OpenMP-b $N
export OMP_NUM_THREADS=8
echo "8 PROCESADOR";
$PBS_O_WORKDIR/pmv-OpenMP-b $N
$PBS_O_WORKDIR/pmv-OpenMP-b $N
$PBS_O_WORKDIR/pmv-OpenMP-b $N
$PBS_O_WORKDIR/pmv-OpenMP-b $N
$PBS_O_WORKDIR/pmv-OpenMP-b $N
$PBS_O_WORKDIR/pmv-OpenMP-b $N
$PBS_O_WORKDIR/pmv-OpenMP-b $N
$PBS_O_WORKDIR/pmv-OpenMP-b $N
$PBS_O_WORKDIR/pmv-OpenMP-b $N
$PBS_O_WORKDIR/pmv-OpenMP-b $N
$PBS_O_WORKDIR/pmv-OpenMP-b $N
$PBS_O_WORKDIR/pmv-OpenMP-b $N
$PBS_O_WORKDIR/pmv-OpenMP-b $N
$PBS_O_WORKDIR/pmv-OpenMP-b $N
$PBS_O_WORKDIR/pmv-OpenMP-b $N
$PBS_O_WORKDIR/pmv-OpenMP-b $N
$PBS_O_WORKDIR/pmv-OpenMP-b $N
$PBS_O_WORKDIR/pmv-OpenMP-b $N
$PBS_O_WORKDIR/pmv-OpenMP-b $N
$PBS_O_WORKDIR/pmv-OpenMP-b $N
export OMP_NUM_THREADS=9
echo "9 PROCESADOR";
$PBS_O_WORKDIR/pmv-OpenMP-b $N
$PBS_O_WORKDIR/pmv-OpenMP-b $N
$PBS_O_WORKDIR/pmv-OpenMP-b $N
$PBS_O_WORKDIR/pmv-OpenMP-b $N
$PBS_O_WORKDIR/pmv-OpenMP-b $N
$PBS_O_WORKDIR/pmv-OpenMP-b $N
$PBS_O_WORKDIR/pmv-OpenMP-b $N
$PBS_O_WORKDIR/pmv-OpenMP-b $N
$PBS_O_WORKDIR/pmv-OpenMP-b $N
$PBS_O_WORKDIR/pmv-OpenMP-b $N
$PBS_O_WORKDIR/pmv-OpenMP-b $N
$PBS_O_WORKDIR/pmv-OpenMP-b $N
$PBS_O_WORKDIR/pmv-OpenMP-b $N
$PBS_O_WORKDIR/pmv-OpenMP-b $N
$PBS_O_WORKDIR/pmv-OpenMP-b $N
$PBS_O_WORKDIR/pmv-OpenMP-b $N
$PBS_O_WORKDIR/pmv-OpenMP-b $N
$PBS_O_WORKDIR/pmv-OpenMP-b $N
$PBS_O_WORKDIR/pmv-OpenMP-b $N
$PBS_O_WORKDIR/pmv-OpenMP-b $N
export OMP_NUM_THREADS=10
echo "10 PROCESADOR";
$PBS_O_WORKDIR/pmv-OpenMP-b $N
$PBS_O_WORKDIR/pmv-OpenMP-b $N
$PBS_O_WORKDIR/pmv-OpenMP-b $N
$PBS_O_WORKDIR/pmv-OpenMP-b $N
$PBS_O_WORKDIR/pmv-OpenMP-b $N
$PBS_O_WORKDIR/pmv-OpenMP-b $N
$PBS_O_WORKDIR/pmv-OpenMP-b $N
$PBS_O_WORKDIR/pmv-OpenMP-b $N
$PBS_O_WORKDIR/pmv-OpenMP-b $N
$PBS_O_WORKDIR/pmv-OpenMP-b $N
$PBS_O_WORKDIR/pmv-OpenMP-b $N
$PBS_O_WORKDIR/pmv-OpenMP-b $N
$PBS_O_WORKDIR/pmv-OpenMP-b $N
$PBS_O_WORKDIR/pmv-OpenMP-b $N
$PBS_O_WORKDIR/pmv-OpenMP-b $N
$PBS_O_WORKDIR/pmv-OpenMP-b $N
$PBS_O_WORKDIR/pmv-OpenMP-b $N
$PBS_O_WORKDIR/pmv-OpenMP-b $N
$PBS_O_WORKDIR/pmv-OpenMP-b $N
$PBS_O_WORKDIR/pmv-OpenMP-b $N
export OMP_NUM_THREADS=11
echo "11 PROCESADOR";
$PBS_O_WORKDIR/pmv-OpenMP-b $N
$PBS_O_WORKDIR/pmv-OpenMP-b $N
$PBS_O_WORKDIR/pmv-OpenMP-b $N
$PBS_O_WORKDIR/pmv-OpenMP-b $N
$PBS_O_WORKDIR/pmv-OpenMP-b $N
$PBS_O_WORKDIR/pmv-OpenMP-b $N
$PBS_O_WORKDIR/pmv-OpenMP-b $N
$PBS_O_WORKDIR/pmv-OpenMP-b $N
$PBS_O_WORKDIR/pmv-OpenMP-b $N
$PBS_O_WORKDIR/pmv-OpenMP-b $N
$PBS_O_WORKDIR/pmv-OpenMP-b $N
$PBS_O_WORKDIR/pmv-OpenMP-b $N
$PBS_O_WORKDIR/pmv-OpenMP-b $N
$PBS_O_WORKDIR/pmv-OpenMP-b $N
$PBS_O_WORKDIR/pmv-OpenMP-b $N
$PBS_O_WORKDIR/pmv-OpenMP-b $N
$PBS_O_WORKDIR/pmv-OpenMP-b $N
$PBS_O_WORKDIR/pmv-OpenMP-b $N
$PBS_O_WORKDIR/pmv-OpenMP-b $N
$PBS_O_WORKDIR/pmv-OpenMP-b $N
export OMP_NUM_THREADS=12
echo "12 PROCESADOR";
$PBS_O_WORKDIR/pmv-OpenMP-b $N
$PBS_O_WORKDIR/pmv-OpenMP-b $N
$PBS_O_WORKDIR/pmv-OpenMP-b $N
$PBS_O_WORKDIR/pmv-OpenMP-b $N
$PBS_O_WORKDIR/pmv-OpenMP-b $N
$PBS_O_WORKDIR/pmv-OpenMP-b $N
$PBS_O_WORKDIR/pmv-OpenMP-b $N
$PBS_O_WORKDIR/pmv-OpenMP-b $N
$PBS_O_WORKDIR/pmv-OpenMP-b $N
$PBS_O_WORKDIR/pmv-OpenMP-b $N
$PBS_O_WORKDIR/pmv-OpenMP-b $N
$PBS_O_WORKDIR/pmv-OpenMP-b $N
$PBS_O_WORKDIR/pmv-OpenMP-b $N
$PBS_O_WORKDIR/pmv-OpenMP-b $N
$PBS_O_WORKDIR/pmv-OpenMP-b $N
$PBS_O_WORKDIR/pmv-OpenMP-b $N
$PBS_O_WORKDIR/pmv-OpenMP-b $N
$PBS_O_WORKDIR/pmv-OpenMP-b $N
$PBS_O_WORKDIR/pmv-OpenMP-b $N
$PBS_O_WORKDIR/pmv-OpenMP-b $N
